### ISSUE TITLE
So, why not G+ location sharing?

### ISSUE THREAD

**Issue by lflee** [neelkadia/WhereaAreYou#1]
https://support.google.com/plus/answer/2998354?hl=en
I have a "location - accurate" circle and a "location - city" circle. I can dynamically put or pull people into or from one of these circles. Once set, your friends and family get your location in just a few taps.

**Comment by neelkadia-zz** [comment]
@lflee, Major hurdle of using G+ I found is, to share and see location of others it **requires** to use Google+. You and your friends need to install a big app on your phone. whereas _WhereAreYou_ can be hosted publicly or privately and you can share the URL, as its on web, anyone can ping and see. You don't need an app for that. Only reporter needs an app to track and upload it to cloud. 

PS : My mother won't use Google+, so purpose was to make a webpage she can visit and check my location without any hurdles. 
a single bookmark - 1, Google+ - 0

**Comment by lflee** [comment]
I see. But (if I understand correctly) it's a bit too complicated that the person who want to share his location needs to build his own stack (app, firebase backend, etc). Just my opinion. Wish your app good luck! 😉

**Comment by neelkadia-zz** [comment]
I did. because I can. :D People can fork and use it, that was my purpose. Thanks @lflee !! :smile:
