### ISSUE TITLE
how?

### ISSUE THREAD

**Issue by User052216** [neelkadia/WhereaAreYou#13]
hello sir. how can i run this in android studio? what file i will import?. please help me reply asap.
i really want to try it but i don't know what to do hope you can help me.

**Comment by neelkadia-zz** [comment]
Hello @User052216 ,
Same like other android projects you've to import the whole Android Project in File -> Import Existing Android Project > Import. Once you import it. You've to upload backend files in any http server. Now you're ready with Android App and it's backend. To connect both, you've to create a Firebase service and which will update a database which is shared by Android App and Web backend.

**Comment by neelkadia-zz** [comment]
Closing this issue. Please refer [Read Me](https://github.com/neelkadia/WhereAreYou/blob/master/ReadMe.md) file for this.

**Comment by User052216** [comment]
than you very much!
