### ISSUE TITLE
Hacktoberfest !!

### ISSUE THREAD

**Issue by neelkadia-zz** [neelkadia/WhereaAreYou#2]
Submit a pull request and get involve in this open source version of FindMyFriend for Android

**Comment by Fofofosho** [comment]
Wanted to make a very similar android app and wanted to get some hacktoberfest credit; so this is a win win project. Do you mind if I help contribute to this project? 

If so, I'm having trouble running with your project setup, specifically with the android folder. Is this currently working in a specific setup? If so could you please include some information for how to get the project imported similar to your environment? Thanks 😄

**Comment by neelkadia-zz** [comment]
Yes please do so.

To configure and run the Android app, you need to make a Firebase project and upload the code there first. When you get configuration of Firebase with Android, add that file in Android app main src. That's how it will configure with the backend and you can use it.

Ping me if you face any issue. I will soon add wiki page for the same project.
